### ISSUE TITLE
If ErrorIgnore=True and errors are encountered,  macro return status should be OK (not error)

### ISSUE THREAD

**Issue by teamdocs** [teamdocs/kantu2018#30] opened 2018-01-23 13:32 UTC
I found this out by running self-test.vbs.

The Demo-Javascript macro in this list contains errrorignore and looks for an image that does not exists.
[Demo-Javascript.zip](https://github.com/teamdocs/kantu2018/files/1656083/Demo-Javascript.zip)

What you see is:

- Play returns error (but should be ok)
- All following macros fail with "A replay is active" error, which makes no sense here. T

hey should replay just fine.

All works if I remove the click command that fails from the  Demo-Javascript macro.

test log:

> 
> Self-Test started at 23/01/2018 10:15:34
> Play OK: Demo-Automate-Forms
> Play OK: Demo-ITA-Flight-Search
> Play OK: Demo-WebScraping
> Play OK: Demo-Variables
> Play OK: Demo-Download
> Play OK: Demo-Upload
> Play OK: Demo-PDF-Extract
> Play OK: Demo-Mouse-Draw
> Play ERROR, Script: Demo-Javascript Error code: -201 Text: command #10 of type Image : Unable to find a match for 'imagenotonwebsite.jpg'
> Play ERROR, Script: Demo-Variables Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Scroll Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Flash Error code: -203 Text: A replay is active

**Comment by kuznetsoffandrey** [comment] 2018-02-11 12:30
Seems it is fixed, but need to be tested.

**Comment by teamdocs** [comment] 2018-02-13 14:26
It is somewhat half fixed... now it works for the FIRST run, but the second run it returns an error:

Test script:

```
'
option Explicit
Dim myKantu, i

'Connect to COM API
set myKantu = CreateObject ("Kantu")
If myKantu Is Nothing Then msgbox ("Couldn't find COM API")

msgbox ("Click OK to start the Kantu Browser now")
i = myKantu.open(true)
if i < 0 then msgbox ("Open Kantu - Error: "+ cstr(i)+ " Text: " +myKantu.getLastError())		

i = myKantu.echo ("Hello from the VBS script")

'By default, Kantu looks for the Kantu-macro (kmacro)  in the /macros folder
'You can also use full path, like myKantu.play("c:\my-files\test.kmacro") 

i = myKantu.play("Demo-Javascript")
msgbox ("Script Replay Error: "+ cstr(i)+ " Text: " +myKantu.getLastError())		

'--------------Second run => error returned!

if i < 0 then msgbox ("Open Kantu - Error: "+ cstr(i)+ " Text: " +myKantu.getLastError())		

i = myKantu.echo ("Test 2")

i = myKantu.play("Demo-Javascript")
msgbox ("Script Replay Error: "+ cstr(i)+ " Text: " +myKantu.getLastError())		



msgbox "Done - Click OK to close the Kantu Browser"
i = myKantu.close

WScript.Quit(i)
```

**Comment by teamdocs** [comment] 2018-02-13 14:28
And with self-test.VBS I get this result

> Self-Test started at 13/02/2018 15:27:25
> Play OK: Demo-Automate-Forms
> Play ERROR, Script: Demo-Javascript Error code: -201 Text: command #10 of type Image : Unable to find a match for 'imagenotonwebsite.jpg' [This is the macro with errorignore]
> Play ERROR, Script: Demo-ITA-Flight-Search Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-WebScraping Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Variables Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Download Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Upload Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-PDF-Extract Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Mouse-Draw Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Variables Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Scroll Error code: -203 Text: A replay is active
> Play ERROR, Script: Demo-Flash Error code: -203 Text: A replay is active

**Comment by kuznetsoffandrey** [comment] 2018-02-17 20:25
Finished!

**Comment by teamdocs** [comment] 2018-02-21 09:34
There is still a bug in the system. The original issue is fixed, but if there is an error once, all other macro runs fail:

Self-Test started at 21/02/2018 10:29:22
Play OK: Demo-Automate-Forms
Play OK: Demo-Javascript
Play OK: Demo-ITA-Flight-Search
Play OK: Demo-WebScraping
Play OK: Demo-Variables
Play OK: Demo-Download
Play OK: Demo-Upload
Play OK: Demo-PDF-Extract
Play ERROR, Script: Demo-Mouse-Draw Error code: -221 Text: App closed by user **[HERE I CLICKED STOP]**
Play ERROR, Script: Demo-Variables Error code: -10 Text: Application closed **<== all the following runs fail instantly afterwards, they do not even run**
Play ERROR, Script: Demo-Scroll Error code: -10 Text: Application closed
Play ERROR, Script: Demo-Flash Error code: -10 Text: Application closed
Open ERROR: -10 Text: Application closed

**Comment by kuznetsoffandrey** [comment] 2018-02-21 10:55
Self-Test started at 21/02/2018 14:51:59
Play OK: Demo-PDF-Extract.kmacro
Play ERROR, Script: Demo-Javascript.kmacro Error code: -220 Text: User pressed stop
Play ERROR, Script: 111.kmacro Error code: -201 Text: command #2 of type DragDrop : Unable to find a match for Image1 'LOIIS.png'. 
Play OK: Demo-Variables.kmacro
Play ERROR, Script: Demo-Scroll.kmacro Error code: -220 Text: User pressed stop
Play OK: Demo-Flash.kmacro


It works for me

I run self-test.vbs, run debug mode, press ok in popup from VBS, another window of kantu is opened (I do NOT close it), then switch to the instance of Kantu, started from debug and stop some macros, the next macros work ok

**Comment by teamdocs** [comment] 2018-02-21 15:56
I am not sure if I understand your test case, but here is a screencast of mine:
https://www.screencast.com/t/huSGSMZ0xgsU

I also checked an updated test routine in the Cef...PIPE project (you see it used in the screencast). I have two versions, one with opening/clising Kantu and one without, both show the same issue

![test1](https://user-images.githubusercontent.com/20772857/36490281-34f99ce8-1728-11e8-81ac-835f318698be.jpg)

**Comment by kuznetsoffandrey** [comment] 2018-02-21 20:21
Speaking about your last test. It seems that client object stays the same in using block, so the inner error string stays the same and doesn't change. That is why other scripts do not change it while we have no error

E.g. Replace only the second macro with some other macro that gives real error, like image not found.
Start the process, stop the 1st macro, let the second and the third macros finish. You will see that 2nd and 3rd will have the same error. So, the problem is in some other place I suppose.

How did you test vbs? Did you replace in current kantu installation folder all the binaries and then run test?

**Comment by kuznetsoffandrey** [comment] 2018-02-21 20:24
I ve just replaced all the binaries and exe in the kantu installation folder and run Self-test.

Self-Test started at 22/02/2018 0:22:24
Play ERROR, Script: Demo-PDF-Extract.kmacro Error code: -220 Text: User pressed stop
Play ERROR, Script: Demo-Javascript.kmacro Error code: -201 Text: command #10 of type Image : Unable to find a match for 'imagenotonwebsite.jpg'
Play ERROR, Script: 111.kmacro Error code: -201 Text: command #3 of type Image : Unable to find a match for 'ZIE8D.png'
Play OK: Demo-Variables.kmacro
Play OK: Demo-Scroll.kmacro
Play OK: Demo-Flash.kmacro

**Closed** 2018-02-21 22:01 UTC
Labels: Blocker

**Comment by teamdocs** [comment] 2018-02-21 22:03
I think I found the remaining issue and fixed it. Simple fix... but strange that this did not show up earlier or maybe it was overlooked.

anyway.. fixed :-)
